# Generated by Django 2.1 on 2018-08-03 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0002_task'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='ConsumerTask',
        ),
        migrations.AlterModelTable(
            name='consumertask',
            table='consumer_tasks',
        ),
    ]
