# Generated by Django 2.1 on 2018-08-03 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consumer', '0005_consumertask_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumertask',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_worker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='consumertask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_consumer', to=settings.AUTH_USER_MODEL),
        ),
    ]
