# Generated by Django 2.1 on 2018-08-03 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0006_auto_20180803_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumertask',
            name='worker',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_worker', to=settings.AUTH_USER_MODEL),
        ),
    ]
